//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceCenter.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceCenter.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Center.
        /// </summary>
        public static string AppNameDisplay {
            get {
                return ResourceManager.GetString("AppNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to connect to your device to set it up. You will temporarily be disconnected from the internet. We will reconnect you as soon as setup is done..
        /// </summary>
        public static string ConnectAlertMessage {
            get {
                return ResourceManager.GetString("ConnectAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you continue.
        /// </summary>
        public static string ConnectAlertTitle {
            get {
                return ResourceManager.GetString("ConnectAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your Ethernet cable to your network. Make sure your PC is on the same network. When you&apos;re ready, click &quot;Find my device&quot;..
        /// </summary>
        public static string ConnectEthernetMessage {
            get {
                return ResourceManager.GetString("ConnectEthernetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet.
        /// </summary>
        public static string ConnectEthernetTitle {
            get {
                return ResourceManager.GetString("ConnectEthernetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find it later, just take me to my devices.
        /// </summary>
        public static string ConnectLater {
            get {
                return ResourceManager.GetString("ConnectLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your finished SD card into the device,.
        /// </summary>
        public static string ConnectMessage1 {
            get {
                return ResourceManager.GetString("ConnectMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then connect your board to the network using Wi-Fi or Ethernet..
        /// </summary>
        public static string ConnectMessage2 {
            get {
                return ResourceManager.GetString("ConnectMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up another device.
        /// </summary>
        public static string ConnectSetupAnotherDevice {
            get {
                return ResourceManager.GetString("ConnectSetupAnotherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SD card is ready..
        /// </summary>
        public static string ConnectTitle {
            get {
                return ResourceManager.GetString("ConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug in your Wi-Fi adapter and boot up your device. Click &quot;Find my device&quot; and it will be automatically detected..
        /// </summary>
        public static string ConnectWiFiMessage1 {
            get {
                return ResourceManager.GetString("ConnectWiFiMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the list of supported Wi-Fi adapters.
        /// </summary>
        public static string ConnectWiFiMessage2 {
            get {
                return ResourceManager.GetString("ConnectWiFiMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi.
        /// </summary>
        public static string ConnectWiFiTitle {
            get {
                return ResourceManager.GetString("ConnectWiFiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, let&apos;s get connected.
        /// </summary>
        public static string ConnetSubTitle {
            get {
                return ResourceManager.GetString("ConnetSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceDetailDeviceNameLabel {
            get {
                return ResourceManager.GetString("DeviceDetailDeviceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string DeviceDetailsApplyButton {
            get {
                return ResourceManager.GetString("DeviceDetailsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change device password.
        /// </summary>
        public static string DeviceDetailsChangePwd {
            get {
                return ResourceManager.GetString("DeviceDetailsChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Portal.
        /// </summary>
        public static string DeviceDetailsDevicePortal {
            get {
                return ResourceManager.GetString("DeviceDetailsDevicePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows System Portal allows you to configure your device in detail.
        /// </summary>
        public static string DeviceDetailsDevicePortalMessage1 {
            get {
                return ResourceManager.GetString("DeviceDetailsDevicePortalMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Device Portal in browser.
        /// </summary>
        public static string DeviceDetailsDevicePortalOpen {
            get {
                return ResourceManager.GetString("DeviceDetailsDevicePortalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string DeviceDetailSettings {
            get {
                return ResourceManager.GetString("DeviceDetailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string DeviceDetailsUserNameAdmin {
            get {
                return ResourceManager.GetString("DeviceDetailsUserNameAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string DeviceDetailsUserNameLabel {
            get {
                return ResourceManager.GetString("DeviceDetailsUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find your device?.
        /// </summary>
        public static string DeviceListCantFindDevice {
            get {
                return ResourceManager.GetString("DeviceListCantFindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string DeviceListColConnection {
            get {
                return ResourceManager.GetString("DeviceListColConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string DeviceListColIPAddress {
            get {
                return ResourceManager.GetString("DeviceListColIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DeviceListColName {
            get {
                return ResourceManager.GetString("DeviceListColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Device Portal.
        /// </summary>
        public static string DeviceListColOpenInDevicePortal {
            get {
                return ResourceManager.GetString("DeviceListColOpenInDevicePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Version.
        /// </summary>
        public static string DeviceListColOSVersion {
            get {
                return ResourceManager.GetString("DeviceListColOSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string DeviceListColSettings {
            get {
                return ResourceManager.GetString("DeviceListColSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DeviceListColType {
            get {
                return ResourceManager.GetString("DeviceListColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter network information.
        /// </summary>
        public static string DeviceListEnterNetworkInfo {
            get {
                return ResourceManager.GetString("DeviceListEnterNetworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string DeviceListLearnMore {
            get {
                return ResourceManager.GetString("DeviceListLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage in Windows Device Portal.
        /// </summary>
        public static string DeviceListManage {
            get {
                return ResourceManager.GetString("DeviceListManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found on the network.
        /// </summary>
        public static string DeviceListNoDevices {
            get {
                return ResourceManager.GetString("DeviceListNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        public static string DeviceListOS {
            get {
                return ResourceManager.GetString("DeviceListOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again.
        /// </summary>
        public static string DeviceListScanAgain {
            get {
                return ResourceManager.GetString("DeviceListScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot device connection.
        /// </summary>
        public static string DeviceListTroubleshoot {
            get {
                return ResourceManager.GetString("DeviceListTroubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string DeviceNamePwdBackButton {
            get {
                return ResourceManager.GetString("DeviceNamePwdBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceNamePwdDeviceNameLabel {
            get {
                return ResourceManager.GetString("DeviceNamePwdDeviceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DeviceNamePwdDoneButton {
            get {
                return ResourceManager.GetString("DeviceNamePwdDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the device name and password helps secure your device.
        /// </summary>
        public static string DeviceNamePwdMessage {
            get {
                return ResourceManager.GetString("DeviceNamePwdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string DeviceNamePwdPassword1 {
            get {
                return ResourceManager.GetString("DeviceNamePwdPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string DeviceNamePwdPassword2 {
            get {
                return ResourceManager.GetString("DeviceNamePwdPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string DeviceNamePwdPassword3 {
            get {
                return ResourceManager.GetString("DeviceNamePwdPassword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string DeviceNamePwdPasswordDontMatch {
            get {
                return ResourceManager.GetString("DeviceNamePwdPasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords match.
        /// </summary>
        public static string DeviceNamePwdPasswordMatch {
            get {
                return ResourceManager.GetString("DeviceNamePwdPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the device name and password.
        /// </summary>
        public static string DeviceNamePwdSubtitle {
            get {
                return ResourceManager.GetString("DeviceNamePwdSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string DeviceNamePwdUserNameLabel {
            get {
                return ResourceManager.GetString("DeviceNamePwdUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Device Architecture.
        /// </summary>
        public static string ErrorUnknownArchitecture {
            get {
                return ResourceManager.GetString("ErrorUnknownArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Windows 10 IoT Core devices on your network.
        /// </summary>
        public static string FindDeviceMessage {
            get {
                return ResourceManager.GetString("FindDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my device.
        /// </summary>
        public static string FindMyDeviceButton {
            get {
                return ResourceManager.GetString("FindMyDeviceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter network information.
        /// </summary>
        public static string FoundDeviceEnterNetworkInfo {
            get {
                return ResourceManager.GetString("FoundDeviceEnterNetworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 wireless device on the network.
        /// </summary>
        public static string FoundDeviceMessage {
            get {
                return ResourceManager.GetString("FoundDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} wireless devices on the network.
        /// </summary>
        public static string FoundDevicesMessage {
            get {
                return ResourceManager.GetString("FoundDevicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a Windows IoT Core device on your network?.
        /// </summary>
        public static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a new device.
        /// </summary>
        public static string IntroSetUpNewDevice {
            get {
                return ResourceManager.GetString("IntroSetUpNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapidly prototype and build your Windows IoT solutions on a variety of devices running Windows 10 IoT Core. Windows 10 gives you powerful tools that let you develop fast and deploy to your device..
        /// </summary>
        public static string IntroSubTitle {
            get {
                return ResourceManager.GetString("IntroSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set up a device, all you need to do is download and install Windows IoT Core to your device.
        /// </summary>
        public static string IntroSubTitle2 {
            get {
                return ResourceManager.GetString("IntroSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the internet of your things.
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string LabelInsecureWifi {
            get {
                return ResourceManager.GetString("LabelInsecureWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this for all future devices.
        /// </summary>
        public static string LabelSaveWifiPassword {
            get {
                return ResourceManager.GetString("LabelSaveWifiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured.
        /// </summary>
        public static string LabelSecureWifi {
            get {
                return ResourceManager.GetString("LabelSecureWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Devices.
        /// </summary>
        public static string LeftBarMyDevices {
            get {
                return ResourceManager.GetString("LeftBarMyDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try some samples.
        /// </summary>
        public static string LeftBarSamples {
            get {
                return ResourceManager.GetString("LeftBarSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a new device.
        /// </summary>
        public static string LeftBarSetUpNewDevice {
            get {
                return ResourceManager.GetString("LeftBarSetUpNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minnow Board Max.
        /// </summary>
        public static string MBM {
            get {
                return ResourceManager.GetString("MBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote device did not respond to request for Access Point list..
        /// </summary>
        public static string MessageUnableToGetWifi {
            get {
                return ResourceManager.GetString("MessageUnableToGetWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless network name.
        /// </summary>
        public static string NetworkCredentialsNetworkNameLabel {
            get {
                return ResourceManager.GetString("NetworkCredentialsNetworkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless password.
        /// </summary>
        public static string NetworkCredentialsPasswordLabel {
            get {
                return ResourceManager.GetString("NetworkCredentialsPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network credentials.
        /// </summary>
        public static string NetworkCredentialsSubTitle {
            get {
                return ResourceManager.GetString("NetworkCredentialsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the.
        /// </summary>
        public static string NewDeviceAcceptLabel {
            get {
                return ResourceManager.GetString("NewDeviceAcceptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you back up any files on your card before proceeding..
        /// </summary>
        public static string NewDeviceAlertMessage {
            get {
                return ResourceManager.GetString("NewDeviceAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing will erase anything previously stored on the card..
        /// </summary>
        public static string NewDeviceAlertMessage2 {
            get {
                return ResourceManager.GetString("NewDeviceAlertMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you continue.
        /// </summary>
        public static string NewDeviceAlertTitle {
            get {
                return ResourceManager.GetString("NewDeviceAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewDeviceCancelDownloading {
            get {
                return ResourceManager.GetString("NewDeviceCancelDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install.
        /// </summary>
        public static string NewDeviceDownloadAndInstall {
            get {
                return ResourceManager.GetString("NewDeviceDownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10 IoT Core.
        /// </summary>
        public static string NewDeviceDownloading {
            get {
                return ResourceManager.GetString("NewDeviceDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB Downloading - {1}%.
        /// </summary>
        public static string NewDeviceDownloadingProgress {
            get {
                return ResourceManager.GetString("NewDeviceDownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DragonBoard 410c comes with its own set of installation tools. After you install Windows and connect this board to the internet, you will find it in &quot;My Devices&quot;..
        /// </summary>
        public static string NewDeviceDragonBoardMessage1 {
            get {
                return ResourceManager.GetString("NewDeviceDragonBoardMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Windows IoT Core on the DragonBoard 410c.
        /// </summary>
        public static string NewDeviceDragonBoardMessage2 {
            get {
                return ResourceManager.GetString("NewDeviceDragonBoardMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string NewDeviceDriveLabel {
            get {
                return ResourceManager.GetString("NewDeviceDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing your SD card.
        /// </summary>
        public static string NewDeviceFlashing {
            get {
                return ResourceManager.GetString("NewDeviceFlashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take a few minutes to complete..
        /// </summary>
        public static string NewDeviceFlashingProgress1 {
            get {
                return ResourceManager.GetString("NewDeviceFlashingProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t remove your SD card..
        /// </summary>
        public static string NewDeviceFlashingProgress2 {
            get {
                return ResourceManager.GetString("NewDeviceFlashingProgress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert an SD card into your computer..
        /// </summary>
        public static string NewDeviceInsertSDCardMessage {
            get {
                return ResourceManager.GetString("NewDeviceInsertSDCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that this process will erase all content on your card..
        /// </summary>
        public static string NewDeviceInsertSDCardMessage2 {
            get {
                return ResourceManager.GetString("NewDeviceInsertSDCardMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the list of recommended SD cards.
        /// </summary>
        public static string NewDeviceRecommendedSDCards {
            get {
                return ResourceManager.GetString("NewDeviceRecommendedSDCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your device type.
        /// </summary>
        public static string NewDeviceSelectDeviceTypeLabel {
            get {
                return ResourceManager.GetString("NewDeviceSelectDeviceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, let&apos;s get Windows 10 IoT Core on your device..
        /// </summary>
        public static string NewDeviceSubTitle {
            get {
                return ResourceManager.GetString("NewDeviceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software license terms.
        /// </summary>
        public static string NewDeviceTermsAndCondition {
            get {
                return ResourceManager.GetString("NewDeviceTermsAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a new device.
        /// </summary>
        public static string NewDeviceTitle {
            get {
                return ResourceManager.GetString("NewDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my credentials.
        /// </summary>
        public static string RememberMyCredentials {
            get {
                return ResourceManager.GetString("RememberMyCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is running on your device..
        /// </summary>
        public static string SamplesAppRunning {
            get {
                return ResourceManager.GetString("SamplesAppRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this app is not running in the foreground, you can press the button below to bring it to foreground..
        /// </summary>
        public static string SamplesAppRunningBackground {
            get {
                return ResourceManager.GetString("SamplesAppRunningBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Hello World&quot; of hardware..
        /// </summary>
        public static string SamplesBlinkyMessage1 {
            get {
                return ResourceManager.GetString("SamplesBlinkyMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle your device&apos;s onboard LED on and off..
        /// </summary>
        public static string SamplesBlinkyMessage2 {
            get {
                return ResourceManager.GetString("SamplesBlinkyMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello blinky.
        /// </summary>
        public static string SamplesBlinkyTitle {
            get {
                return ResourceManager.GetString("SamplesBlinkyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy and run.
        /// </summary>
        public static string SamplesDeployAndRunButton {
            get {
                return ResourceManager.GetString("SamplesDeployAndRunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying....
        /// </summary>
        public static string SamplesDeploying {
            get {
                return ResourceManager.GetString("SamplesDeploying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string SamplesDeviceLabel {
            get {
                return ResourceManager.GetString("SamplesDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download code from GitHub.
        /// </summary>
        public static string SamplesDownload {
            get {
                return ResourceManager.GetString("SamplesDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string SamplesForegroundButton {
            get {
                return ResourceManager.GetString("SamplesForegroundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about what you can do.
        /// </summary>
        public static string SamplesLearnMore {
            get {
                return ResourceManager.GetString("SamplesLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at other projects and tutorials.
        /// </summary>
        public static string SamplesOtherProjects {
            get {
                return ResourceManager.GetString("SamplesOtherProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn your Windows IoT Core device into an internet radio that can be controlled from anywhere in your home..
        /// </summary>
        public static string SamplesRadioMessage1 {
            get {
                return ResourceManager.GetString("SamplesRadioMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet radio.
        /// </summary>
        public static string SamplesRadioTitle {
            get {
                return ResourceManager.GetString("SamplesRadioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this app on your device.
        /// </summary>
        public static string SamplesRun {
            get {
                return ResourceManager.GetString("SamplesRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start coding.
        /// </summary>
        public static string SamplesStartCoding {
            get {
                return ResourceManager.GetString("SamplesStartCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string SamplesStopButton {
            get {
                return ResourceManager.GetString("SamplesStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy and run sample apps on your device.
        /// </summary>
        public static string SamplesSubTitle {
            get {
                return ResourceManager.GetString("SamplesSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try some samples.
        /// </summary>
        public static string SamplesTitle {
            get {
                return ResourceManager.GetString("SamplesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the tutorial online.
        /// </summary>
        public static string SamplesTutorialOnline {
            get {
                return ResourceManager.GetString("SamplesTutorialOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Device Portal in browser.
        /// </summary>
        public static string SuccessAction1 {
            get {
                return ResourceManager.GetString("SuccessAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the tools.
        /// </summary>
        public static string SuccessAction2 {
            get {
                return ResourceManager.GetString("SuccessAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore projects and tutorials.
        /// </summary>
        public static string SuccessAction3 {
            get {
                return ResourceManager.GetString("SuccessAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your device in Windows Device Portal.
        /// </summary>
        public static string SuccessMessage1 {
            get {
                return ResourceManager.GetString("SuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your PC.
        /// </summary>
        public static string SuccessMessage2 {
            get {
                return ResourceManager.GetString("SuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your first Windows app.
        /// </summary>
        public static string SuccessMessage3 {
            get {
                return ResourceManager.GetString("SuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re ready to start developing..
        /// </summary>
        public static string SuccessSubTitle {
            get {
                return ResourceManager.GetString("SuccessSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! {0} is online..
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the list of recommended SD cards.
        /// </summary>
        public static string ViewAcceptableSDCards {
            get {
                return ResourceManager.GetString("ViewAcceptableSDCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string WifiBackButton {
            get {
                return ResourceManager.GetString("WifiBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WifiNextButton {
            get {
                return ResourceManager.GetString("WifiNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this for all future devices.
        /// </summary>
        public static string WifiRepeatForFutureDevices {
            get {
                return ResourceManager.GetString("WifiRepeatForFutureDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the networks your device can see.
        /// </summary>
        public static string WifiSubTitle {
            get {
                return ResourceManager.GetString("WifiSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi.
        /// </summary>
        public static string WifiTitle {
            get {
                return ResourceManager.GetString("WifiTitle", resourceCulture);
            }
        }
    }
}
