//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceCenter.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceCenter.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Center.
        /// </summary>
        public static string AppNameDisplay {
            get {
                return ResourceManager.GetString("AppNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to connect to your device to set it up. You will temporarily be disconnected from the internet. We will reconnect you as soon as setup is done..
        /// </summary>
        public static string ConnectAlertMessage {
            get {
                return ResourceManager.GetString("ConnectAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you continue.
        /// </summary>
        public static string ConnectAlertTitle {
            get {
                return ResourceManager.GetString("ConnectAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect via Wi-Fi.
        /// </summary>
        public static string ConnectHelpMessage1 {
            get {
                return ResourceManager.GetString("ConnectHelpMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect using an Ethernet cable.
        /// </summary>
        public static string ConnectHelpMessage2 {
            get {
                return ResourceManager.GetString("ConnectHelpMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect later.
        /// </summary>
        public static string ConnectHelpMessage3 {
            get {
                return ResourceManager.GetString("ConnectHelpMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need more help?.
        /// </summary>
        public static string ConnectHelpSubTitle {
            get {
                return ResourceManager.GetString("ConnectHelpSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, insert your finished SD card into the device..
        /// </summary>
        public static string ConnectMessage1 {
            get {
                return ResourceManager.GetString("ConnectMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, connect your board to the network using Wi-Fi or Ethernet..
        /// </summary>
        public static string ConnectMessage2 {
            get {
                return ResourceManager.GetString("ConnectMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SD card is ready..
        /// </summary>
        public static string ConnectTitle {
            get {
                return ResourceManager.GetString("ConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, let&apos;s get connected.
        /// </summary>
        public static string ConnetSubTitle {
            get {
                return ResourceManager.GetString("ConnetSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find your device?.
        /// </summary>
        public static string DeviceListCantFindDevice {
            get {
                return ResourceManager.GetString("DeviceListCantFindDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter network information.
        /// </summary>
        public static string DeviceListEnterNetworkInfo {
            get {
                return ResourceManager.GetString("DeviceListEnterNetworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage in Windows Device Portal.
        /// </summary>
        public static string DeviceListManage {
            get {
                return ResourceManager.GetString("DeviceListManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again.
        /// </summary>
        public static string DeviceListScanAgain {
            get {
                return ResourceManager.GetString("DeviceListScanAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot device connection.
        /// </summary>
        public static string DeviceListTroubleshoot {
            get {
                return ResourceManager.GetString("DeviceListTroubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceNamePwdDeviceNameLabel {
            get {
                return ResourceManager.GetString("DeviceNamePwdDeviceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the device name and password helps secure your device.
        /// </summary>
        public static string DeviceNamePwdMessage {
            get {
                return ResourceManager.GetString("DeviceNamePwdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DeviceNamePwdPassword1 {
            get {
                return ResourceManager.GetString("DeviceNamePwdPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DeviceNamePwdPassword2 {
            get {
                return ResourceManager.GetString("DeviceNamePwdPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string DeviceNamePwdPasswordDontMatch {
            get {
                return ResourceManager.GetString("DeviceNamePwdPasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords match.
        /// </summary>
        public static string DeviceNamePwdPasswordMatch {
            get {
                return ResourceManager.GetString("DeviceNamePwdPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the device name and password.
        /// </summary>
        public static string DeviceNamePwdSubtitle {
            get {
                return ResourceManager.GetString("DeviceNamePwdSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string DeviceNamePwdUserNameLabel {
            get {
                return ResourceManager.GetString("DeviceNamePwdUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Windows 10 IoT Core devices on your network.
        /// </summary>
        public static string FindDeviceMessage {
            get {
                return ResourceManager.GetString("FindDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my device.
        /// </summary>
        public static string FindMyDeviceButton {
            get {
                return ResourceManager.GetString("FindMyDeviceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter network information.
        /// </summary>
        public static string FoundDeviceEnterNetworkInfo {
            get {
                return ResourceManager.GetString("FoundDeviceEnterNetworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 wireless device on the network.
        /// </summary>
        public static string FoundDeviceMessage {
            get {
                return ResourceManager.GetString("FoundDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} wireless devices on the network.
        /// </summary>
        public static string FoundDevicesMessage {
            get {
                return ResourceManager.GetString("FoundDevicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a Windows IoT Core device on your network?.
        /// </summary>
        public static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a new device.
        /// </summary>
        public static string IntroSetUpNewDevice {
            get {
                return ResourceManager.GetString("IntroSetUpNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapidly prototype and build your Windows IoT solutions on a variety of devices running Windows 10 IoT Core. Windows 10 gives you powerful tools that let you develop fast and deploy to your device..
        /// </summary>
        public static string IntroSubTitle {
            get {
                return ResourceManager.GetString("IntroSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the internet of your things.
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless network name.
        /// </summary>
        public static string NetworkCredentialsNetworkNameLabel {
            get {
                return ResourceManager.GetString("NetworkCredentialsNetworkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless password.
        /// </summary>
        public static string NetworkCredentialsPasswordLabel {
            get {
                return ResourceManager.GetString("NetworkCredentialsPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network credentials.
        /// </summary>
        public static string NetworkCredentialsSubTitle {
            get {
                return ResourceManager.GetString("NetworkCredentialsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the.
        /// </summary>
        public static string NewDeviceAcceptLabel {
            get {
                return ResourceManager.GetString("NewDeviceAcceptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you back up any files on your card before proceeding. Flashing will erase anything previously stored on the card..
        /// </summary>
        public static string NewDeviceAlertMessage {
            get {
                return ResourceManager.GetString("NewDeviceAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you continue.
        /// </summary>
        public static string NewDeviceAlertTitle {
            get {
                return ResourceManager.GetString("NewDeviceAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install.
        /// </summary>
        public static string NewDeviceDownloadAndInstall {
            get {
                return ResourceManager.GetString("NewDeviceDownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Windows 10 IoT Core.
        /// </summary>
        public static string NewDeviceDownloading {
            get {
                return ResourceManager.GetString("NewDeviceDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string NewDeviceDriveLabel {
            get {
                return ResourceManager.GetString("NewDeviceDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing your SD card.
        /// </summary>
        public static string NewDeviceFlashing {
            get {
                return ResourceManager.GetString("NewDeviceFlashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert an SD card into your computer. Note that this process will erase all content on your card..
        /// </summary>
        public static string NewDeviceInsertSDCardMessage {
            get {
                return ResourceManager.GetString("NewDeviceInsertSDCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your device type.
        /// </summary>
        public static string NewDeviceSelectDeviceTypeLabel {
            get {
                return ResourceManager.GetString("NewDeviceSelectDeviceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, let&apos;s get Windows 10 IoT Core on your device..
        /// </summary>
        public static string NewDeviceSubTitle {
            get {
                return ResourceManager.GetString("NewDeviceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        public static string NewDeviceTermsAndCondition {
            get {
                return ResourceManager.GetString("NewDeviceTermsAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a new device.
        /// </summary>
        public static string NewDeviceTitle {
            get {
                return ResourceManager.GetString("NewDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Device Portal in browser.
        /// </summary>
        public static string SuccessAction1 {
            get {
                return ResourceManager.GetString("SuccessAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the tools.
        /// </summary>
        public static string SuccessAction2 {
            get {
                return ResourceManager.GetString("SuccessAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore projects and tutorials.
        /// </summary>
        public static string SuccessAction3 {
            get {
                return ResourceManager.GetString("SuccessAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your device in Windows Device Portal.
        /// </summary>
        public static string SuccessMessage1 {
            get {
                return ResourceManager.GetString("SuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your PC.
        /// </summary>
        public static string SuccessMessage2 {
            get {
                return ResourceManager.GetString("SuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your first Windows app.
        /// </summary>
        public static string SuccessMessage3 {
            get {
                return ResourceManager.GetString("SuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re ready to start developing..
        /// </summary>
        public static string SuccessSubTitle {
            get {
                return ResourceManager.GetString("SuccessSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! {0} is online..
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Content?.
        /// </summary>
        public static string TitleEraseContent {
            get {
                return ResourceManager.GetString("TitleEraseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the list of recommended SD cards.
        /// </summary>
        public static string ViewAcceptableSDCards {
            get {
                return ResourceManager.GetString("ViewAcceptableSDCards", resourceCulture);
            }
        }
    }
}
